version: '3'
services:
  db:
    image: postgres
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:4.0.9-alpine'
    command: redis-server
    ports:
      - 6379
    volumes:
      - 'redis:/var/lib/redis/data'
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myroscope
    ports:
      - "3000:3000"
    environment:
      - SEED_USER_EMAIL
      - SEED_USER_PASS
    depends_on:
      - db
      - redis
  sidekiq:
    build: .
    command: bundle exec sidekiq -q default -q mailers
    volumes:
      - '.:/myroscope'
    environment:
        - REDIS_URL
    depends_on:
      - db
      - redis
volumes:
  postgres: {}
  redis: {}
